service: vwcsays
app: vwcsays
org: bmw2621
provider:
  name: aws
  runtime: nodejs12.x
stage: dev
region: us-east-1
package:
  excludeDevDependencies: false
plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-apigw-binary
  - serverless-apigwy-binary
custom:
  apigwBinary:
    types:           #list of mime-types
      - 'image/jpg'
      - 'image/jpeg'
      - 'image/png'
functions:
  jeromeSays:
    handler: handler.jeromeSays
    events:
      - http:
          path: /jeromeSays
          method: post
          contentHandling: CONVERT_TO_BINARY
          request:
            parameters:
              queryStrings:
                text: true
  jodySays:
    handler: handler.jodySays
    events:
      - http:
          path: /jodySays/{jodytype}
          method: post
          contentHandling: CONVERT_TO_BINARY
          request:
            parameters:
              queryStrings:
                text: true
              paths:
                jodytype: true
